#ifndef UI_H
#define UI_H

#define SPRITE_VRAM_INDEX_EMPTY 0x00
#define SPRITE_VRAM_INDEX_ANGLE_TOP_LEFT 0x01
#define SPRITE_VRAM_INDEX_LINE_TOP 0x02
#define SPRITE_VRAM_INDEX_ANGLE_TOP_RIGHT 0x03
#define SPRITE_VRAM_INDEX_LINE_LEFT 0x04
#define SPRITE_VRAM_INDEX_LINE_RIGHT 0x05
#define SPRITE_VRAM_INDEX_LINE_BOTTOM 0x06
#define SPRITE_VRAM_INDEX_ANGLE_BOTTOM_RIGHT 0x07
#define SPRITE_VRAM_INDEX_ANGLE_BOTTOM_LEFT 0x08
#define SPRITE_VRAM_INDEX_HEART 0x09
#define SPRITE_VRAM_INDEX_CLOCK 0x0A

#define SPRITE_VRAM_INDEX_TOTAL 0x0B

extern const unsigned char backgroundTiles[];
extern const unsigned char backgroundMap[];

#endif // UI_H
